### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Mikaciu** [Mikaciu/recursemp3#2]
- [ ] parametrize the number of threads / HTTP connection pool size via a '--' switch
- [ ] implement the debug mode (the switch is present but it doesn't do much)
- [x] externalize the output functions (OUT, WRN, DBG, ERR) into a single class
